### ISSUE TITLE
How to get a gen in Shopgui+

### ISSUE THREAD

**Issue by LunarSkillz** [stam2020/SimpleGenerators#3]
Im building a gen server! I use simple generators but I now need to get a gen in shopgui+ How do I do that I already tried these methods:
- Added the gen name in the config
- Searched google

Could someone help me?

**Comment by stam2020** [comment]
For a generator to be recognized by the plugin, both its name and lore must be correct. Make sure the shopgui+ doesn't lose the details. If you want to know how to add lore to items, that's more of a shopgui+ question, so ask there.
